### ISSUE TITLE
网站访问不了啦

### ISSUE THREAD

**Issue by zifeixu85** [rhettor/foodguide-zh_CN#1]

**Comment by rhettor** [comment]
@zifeixu85 vps到期了，你可以clone下来在本地打开

**Comment by zifeixu85** [comment]
已经在本地打开，可惜分享给小伙伴不方便，你可以试着放到 github pages 里面，我的一些静态页面就是这样放的

**Comment by rhettor** [comment]
@zifeixu85 已更新到http://rhettor.github.io/foodguide-zh_CN/html/
